### ISSUE TITLE
Can't run bm anymore

### ISSUE THREAD

**Issue by gomezhyuuga** [DeMille/bookmark#1]
After adding the alias in the ~/.bashrc I got the next error:

```
~ ❯ bm list
listBookmark:1: no such file or directory: node /Users/lib/node_modules/bookmark/index.js

~ ❯ bm -h
getHelp:1: no such file or directory: node /Users/lib/node_modules/bookmark/index.js

~ ❯ bm add something
addBookmark:7: no such file or directory: node /Users/lib/node_modules/bookmark/index.js

```

**OS:** OS X 10.11.1
**Node.js:** v5.0.0
**npm:** v3.3.9
**Shell:** zsh 5.0.8 (x86_64-apple-darwin15.0)

**Comment by chrisspiegl** [comment]
Experiencing the same problem here. Would love to see a fix for it.

**Comment by DeMille** [comment]
Okay, I think I have a fix. Sorry this is way late. Were you both using zsh? I actually never had zsh sorted out because of some shell script differences. I've updated the scripts now and zsh should work.

There was also some problems with path escaping that I noticed after I started using nvm. Those should be fixed too, if those affected you.
